In [1]:
from skimage import morphology
import numpy as np

In [2]:
a = np.array([[0, 0, 0, 1, 0],
              [1, 1, 1, 0, 0],
              [1, 1, 1, 0, 0],
              [0, 0, 0, 1, 1]], bool)

In [3]:
b = morphology.remove_small_objects(a, 2)
b

array([[False, False, False, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [False, False, False,  True,  True]])

In [4]:
c = morphology.remove_small_objects(a, 6, connectivity=1)
c

array([[False, False, False, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [False, False, False, False, False]])

In [5]:
c = morphology.remove_small_objects(a, 6, connectivity=2)
c

array([[False, False, False,  True, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [False, False, False,  True,  True]])

In [6]:
d = morphology.remove_small_objects(a, 6, in_place=True)
d

array([[False, False, False, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [False, False, False, False, False]])